#Part1

In [3]:
import numpy as np

In [11]:
#1d Array
a=np.array([1, 2, 3, 4, 5])

#2d Array
b=np.array([[1, 2, 3], [4, 5, 6]])

#3d Array
c=np.array([[[1, 2], [3, 6], [4, 5]]])
type(a)
print(a.size)
print(b.size)
print(c.size)
print(a.shape)
print(b.shape)
print(c.shape)
print(a.dtype)
print(b.dtype)
print(c.dtype)

5
6
6
(5,)
(2, 3)
(1, 3, 2)
int64
int64
int64


In [12]:
d=np.array([[1, 2.4], [3.9, 6]])
print(d.dtype)

float64


In [13]:
d.transpose()

array([[1. , 3.9],
       [2.4, 6. ]])

#Part 2

In [19]:
# np.empty((rows, cols), dtype)
np.empty((4, 4), dtype = int)

array([[23925768161198147, 32370111954616435, 27584964334190684,
        30399731283525737],
       [25896191785042017, 34058953225207854, 30962724186357876,
        31244212048494684],
       [28429436511125606, 28710881422737503, 32651561162571873,
        32370073300107356],
       [34058961815535732, 30399782823591982, 12666807751278697,
        32088649863463018]])

In [20]:
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [21]:
np.ones((3, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [22]:
np.ones((3, 5), dtype = int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [23]:
# np.zeros, exactly same as ones

In [25]:
np.ones((3, 4), dtype = bool)
np.zeros((3, 4), dtype = bool)

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [26]:
np.ones((3, 4), dtype = str)

array([['1', '1', '1', '1'],
       ['1', '1', '1', '1'],
       ['1', '1', '1', '1']], dtype='<U1')

In [27]:
np.zeros((3, 4), dtype = str)

array([['', '', '', ''],
       ['', '', '', ''],
       ['', '', '', '']], dtype='<U1')

#Part3

In [28]:
#np.arange(start, end, step)
np.arange(1, 20)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [29]:
np.arange(1, 20, 3)

array([ 1,  4,  7, 10, 13, 16, 19])

In [32]:
#arr.reshape((rows, cols))
a=np.arange(2, 20, 2)
a.reshape((3, 3)) #doesn't change the original array

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [37]:
b=np.arange(1, 100, 2)
b.reshape((10, 5))

array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19],
       [21, 23, 25, 27, 29],
       [31, 33, 35, 37, 39],
       [41, 43, 45, 47, 49],
       [51, 53, 55, 57, 59],
       [61, 63, 65, 67, 69],
       [71, 73, 75, 77, 79],
       [81, 83, 85, 87, 89],
       [91, 93, 95, 97, 99]])

In [38]:
b.flatten()

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [39]:
a.ravel() #it changes the original array itself so is faster than flatten, since it doesn't consume ay extra memory.

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

#Part4

In [40]:
a=np.arange(1, 51)
a=a.reshape(10, 5)
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45],
       [46, 47, 48, 49, 50]])

In [44]:
a[0]
a[2:5]
a[:, 2]
a[:, 2:5]

array([[ 3,  4,  5],
       [ 8,  9, 10],
       [13, 14, 15],
       [18, 19, 20],
       [23, 24, 25],
       [28, 29, 30],
       [33, 34, 35],
       [38, 39, 40],
       [43, 44, 45],
       [48, 49, 50]])

#Part5

In [47]:
a=np.arange(0, 18).reshape((6, 3))
b=np.arange(20, 38).reshape((6, 3))
print(a)
print(b)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[20 21 22]
 [23 24 25]
 [26 27 28]
 [29 30 31]
 [32 33 34]
 [35 36 37]]


array([[20, 22, 24],
       [26, 28, 30],
       [32, 34, 36],
       [38, 40, 42],
       [44, 46, 48],
       [50, 52, 54]])

In [48]:
a+b

array([[20, 22, 24],
       [26, 28, 30],
       [32, 34, 36],
       [38, 40, 42],
       [44, 46, 48],
       [50, 52, 54]])

In [50]:
np.add(a,b)

array([[20, 22, 24],
       [26, 28, 30],
       [32, 34, 36],
       [38, 40, 42],
       [44, 46, 48],
       [50, 52, 54]])

In [51]:
np.subtract(a, b)

array([[-20, -20, -20],
       [-20, -20, -20],
       [-20, -20, -20],
       [-20, -20, -20],
       [-20, -20, -20],
       [-20, -20, -20]])

In [52]:
a-b

array([[-20, -20, -20],
       [-20, -20, -20],
       [-20, -20, -20],
       [-20, -20, -20],
       [-20, -20, -20],
       [-20, -20, -20]])

In [53]:
a*b

array([[  0,  21,  44],
       [ 69,  96, 125],
       [156, 189, 224],
       [261, 300, 341],
       [384, 429, 476],
       [525, 576, 629]])

In [54]:
np.multiply(a, b)

array([[  0,  21,  44],
       [ 69,  96, 125],
       [156, 189, 224],
       [261, 300, 341],
       [384, 429, 476],
       [525, 576, 629]])

In [55]:
a/b

array([[0.        , 0.04761905, 0.09090909],
       [0.13043478, 0.16666667, 0.2       ],
       [0.23076923, 0.25925926, 0.28571429],
       [0.31034483, 0.33333333, 0.35483871],
       [0.375     , 0.39393939, 0.41176471],
       [0.42857143, 0.44444444, 0.45945946]])

In [56]:
np.divide(a, b)

array([[0.        , 0.04761905, 0.09090909],
       [0.13043478, 0.16666667, 0.2       ],
       [0.23076923, 0.25925926, 0.28571429],
       [0.31034483, 0.33333333, 0.35483871],
       [0.375     , 0.39393939, 0.41176471],
       [0.42857143, 0.44444444, 0.45945946]])

In [58]:
#for matrix multiplication use @
a=np.arange(0, 18).reshape((3, 6))
b=np.arange(20, 38).reshape((6, 3))
a@b

array([[ 465,  480,  495],
       [1455, 1506, 1557],
       [2445, 2532, 2619]])

In [59]:
a.dot(b) #inbuilt function for matrix multiplication

array([[ 465,  480,  495],
       [1455, 1506, 1557],
       [2445, 2532, 2619]])

In [64]:
a.max()
b.max()
a.argmax() #returns index of max element

np.int64(17)

In [65]:
#axis = 1 means rows, axis = 0 means columns
np.sum(a, axis=1) 

array([15, 51, 87])

In [66]:
np.sum(a, axis=0)

array([18, 21, 24, 27, 30, 33])

In [67]:
np.mean(b)

np.float64(28.5)

In [68]:
np.sqrt(b)

array([[4.47213595, 4.58257569, 4.69041576],
       [4.79583152, 4.89897949, 5.        ],
       [5.09901951, 5.19615242, 5.29150262],
       [5.38516481, 5.47722558, 5.56776436],
       [5.65685425, 5.74456265, 5.83095189],
       [5.91607978, 6.        , 6.08276253]])

In [69]:
np.std(b)

np.float64(5.188127472091127)

In [70]:
np.log(b)

array([[2.99573227, 3.04452244, 3.09104245],
       [3.13549422, 3.17805383, 3.21887582],
       [3.25809654, 3.29583687, 3.33220451],
       [3.36729583, 3.40119738, 3.4339872 ],
       [3.4657359 , 3.49650756, 3.52636052],
       [3.55534806, 3.58351894, 3.61091791]])

#Part6

In [4]:
np.pi

3.141592653589793

In [5]:
np.sin(np.pi/2)

np.float64(1.0)

In [6]:
np.cos(np.pi/2)

np.float64(6.123233995736766e-17)

In [7]:
np.tan(np.pi/2)

np.float64(1.633123935319537e+16)

#Part7

In [8]:
np.random.random(1)

array([0.7429023])

In [9]:
np.random.random((2, 2))

array([[0.72764319, 0.73586237],
       [0.49850043, 0.43543915]])

In [10]:
np.random.randint(1, 10)

2

In [11]:
np.random.randint(1, 10, (3, 4, 5))

array([[[4, 2, 3, 5, 8],
        [3, 1, 3, 5, 2],
        [5, 7, 9, 3, 2],
        [5, 3, 9, 9, 2]],

       [[3, 4, 2, 3, 4],
        [7, 4, 1, 4, 8],
        [4, 1, 9, 7, 5],
        [9, 2, 6, 5, 2]],

       [[8, 7, 6, 3, 7],
        [4, 4, 3, 7, 4],
        [6, 1, 4, 2, 4],
        [2, 5, 5, 5, 6]]], dtype=int32)

In [12]:
np.random.rand(2, 2)

array([[0.8924213 , 0.53942736],
       [0.60939417, 0.96657665]])

In [13]:
np.random.randn(2, 2) #for negative values

array([[-0.90634004,  0.32817525],
       [ 1.41738002,  0.27612632]])

In [14]:
a=np.arange(1, 10)
np.random.choice(a)

np.int64(3)

#Part 8